import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import { getAllSlugs, getPostBySlug } from "@/lib/blog";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { BlogPostContent } from "@/components/blog/BlogPostContent";

const BASE_URL = process.env.NEXT_PUBLIC_BASE_URL ?? "https://sloerstudio.com";

export async function generateStaticParams() {
  return getAllSlugs().map((slug) => ({ slug }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}): Promise<Metadata> {
  const { slug } = await params;
  const post = getPostBySlug(slug);
  if (!post) return { title: "Post not found — SloerStudio" };

  const { frontmatter: fm } = post;
  const url = `${BASE_URL}/blog/${fm.slug}`;

  return {
    title: fm.title,
    description: fm.excerpt,
    keywords: [
      ...fm.tags,
      "SloerStudio",
      "AI video generation",
      "Remotion",
      "programmatic video",
      "creative infrastructure",
    ],
    authors: [{ name: fm.author }],
    openGraph: {
      type: "article",
      title: fm.title,
      description: fm.excerpt,
      url,
      siteName: "SloerStudio",
      locale: "en_US",
      publishedTime: fm.date,
      authors: [fm.author],
      tags: fm.tags,
    },
    twitter: {
      card: "summary_large_image",
      title: fm.title,
      description: fm.excerpt,
      site: "@sloerstudio",
    },
    alternates: {
      canonical: url,
    },
  };
}

export default async function BlogPostPage({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const post = getPostBySlug(slug);
  if (!post) notFound();

  const { frontmatter: fm, content } = post;
  const url = `${BASE_URL}/blog/${fm.slug}`;

  const jsonLd = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: fm.title,
    description: fm.excerpt,
    datePublished: fm.date,
    dateModified: fm.date,
    author: {
      "@type": "Organization",
      name: fm.author,
      url: BASE_URL,
    },
    publisher: {
      "@type": "Organization",
      name: "SloerStudio",
      url: BASE_URL,
    },
    mainEntityOfPage: {
      "@type": "WebPage",
      "@id": url,
    },
    keywords: fm.tags.join(", "),
    articleSection: "Technology",
    inLanguage: "en-US",
    isAccessibleForFree: true,
  };

  return (
    <div className="min-h-screen bg-[#050505] text-white">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />
      <Navbar />
      <main className="mx-auto max-w-3xl px-6 pb-20 pt-10" role="main">
        {/* Back link */}
        <Link
          href="/blog"
          className="mb-8 inline-flex items-center gap-2 text-sm text-gray-400 transition-colors hover:text-white"
          aria-label="Back to blog"
        >
          ← Back to blog
        </Link>

        {/* Article header */}
        <header className="mb-10">
          <div className="mb-4 flex flex-wrap items-center gap-3 text-sm text-gray-500">
            <time dateTime={fm.date}>
              {new Date(fm.date).toLocaleDateString("en-US", {
                year: "numeric",
                month: "long",
                day: "numeric",
              })}
            </time>
            <span aria-hidden="true">·</span>
            <span>{fm.readingTime}</span>
            {fm.generatedBy && (
              <>
                <span aria-hidden="true">·</span>
                <span className="text-[#28e7c5]">Generated by {fm.generatedBy}</span>
              </>
            )}
          </div>
          <h1 className="font-display text-3xl font-bold tracking-[-0.03em] text-white sm:text-4xl md:text-5xl">
            {fm.title}
          </h1>
          <p className="mt-4 text-lg leading-8 text-gray-400">{fm.excerpt}</p>
          <div className="mt-5 flex flex-wrap gap-2">
            {fm.tags.map((tag) => (
              <span
                key={tag}
                className="rounded-full border border-white/[0.06] bg-white/[0.03] px-3 py-1 text-xs text-gray-500"
              >
                {tag}
              </span>
            ))}
          </div>
        </header>

        {/* MDX content */}
        <article className="prose-invert">
          <BlogPostContent
            source={content}
            title={fm.title}
            accent={fm.coverAccent}
          />
        </article>
      </main>
      <Footer />
    </div>
  );
}
